"""翼型まわりの O 型格子を自前で生成して ``polyMesh`` に書き出す.

なぜ blockMesh を使わないか
---------------------------
``blockMesh`` で O 型格子を組むには「断面の各点を中心から放射状に外へ
飛ばす」しかないが, これは断面が中心について **星形** (star-shaped) で
ないと成立しない. キャンバ 7 %・厚み 9 % の StampFly 1209 の断面では

* 1/4 コード点 ``(0.25, 0)`` は断面の **外**に出る (下面が持ち上がる)
* 図心を使っても後半下面で偏角が逆行する (放射線が表面をかすめる)

ため, どこに中心を置いても格子が裏返る. 実際 blockMesh は
``is inside-out`` / ``has inward-pointing faces`` で落ちる.

そこで **法線方向の押し出しを遠方円へブレンドする** 代数格子を自前で作り,
``constant/polyMesh`` を直接書く. 利点:

* 壁近傍が表面に直交するので境界層の分解能が素直に効く
* 薄い・キャンバの大きい断面でも破綻しない
* blockMesh に依存しないので OpenFOAM のバージョン差の影響を受けない
* セル面積の正値性をこちらで検査できる (テスト可能)

格子の作り方
------------
半径方向パラメータ ``t_k`` (等比分布, ``t_0 = 0``, ``t_n = 1``) に対し

    A_i(k) = p_i + n_i * L_k                     (法線押し出し)
    S_i(k) = p_i + (O_i - p_i) * t_k             (遠方円へ向かう直線)
    X_i(k) = (1 - b_k) A_i(k) + b_k S_i(k)

``b_k`` は壁からの距離 ``L_k`` の smoothstep で, ``normal_length`` までは
法線押し出し, それ以降は遠方円への直線に滑らかに移る. ``O_i`` は弧長で
割り付けた円周上の点なので, 最外層はちょうど円になる.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

__all__ = ["ogrid_nodes", "write_polymesh", "cell_areas"]

_HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| generated by prop_sim.cfd.mesh                                              |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "constant/polyMesh";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def _node_normals(p: np.ndarray) -> np.ndarray:
    """閉曲線 (反時計回り) の各点における外向き単位法線."""
    nxt = np.roll(p, -1, axis=0)
    prv = np.roll(p, 1, axis=0)
    t1, t2 = nxt - p, p - prv
    # 反時計回りなら外向きは進行方向の右手側 (ty, -tx)
    n1 = np.stack([t1[:, 1], -t1[:, 0]], axis=1)
    n2 = np.stack([t2[:, 1], -t2[:, 0]], axis=1)
    n1 /= np.linalg.norm(n1, axis=1, keepdims=True)
    n2 /= np.linalg.norm(n2, axis=1, keepdims=True)
    n = n1 + n2
    return n / np.linalg.norm(n, axis=1, keepdims=True)


def _geometric(n: int, total: float, grading: float) -> np.ndarray:
    """``n`` セル・全長 ``total``・(最外 / 最内) = ``grading`` の累積座標."""
    if n < 1:
        raise ValueError("n_radial >= 1 が必要です")
    if n == 1 or abs(grading - 1.0) < 1e-12:
        return np.linspace(0.0, total, n + 1)
    r = grading ** (1.0 / (n - 1))
    h = total * (r - 1.0) / (r**n - 1.0)
    return np.concatenate([[0.0], np.cumsum(h * r ** np.arange(n))])


def ogrid_nodes(
    points: np.ndarray,
    *,
    n_radial: int = 120,
    far_field_radius: float = 40.0,
    radial_grading: float = 2000.0,
    normal_length: float = 0.5,
    smooth_passes: int = 120,
    smooth_weight: float = 0.5,
    centre=None,
) -> np.ndarray:
    """O 型格子の節点を ``(n_theta, n_radial + 1, 2)`` で返す.

    ``points`` は反時計回りの閉曲線 (重複点なし).
    """
    p = np.asarray(points, float)
    if p.ndim != 2 or p.shape[1] != 2:
        raise ValueError("points は (N, 2) である必要があります")
    nt = p.shape[0]
    centre = p.mean(axis=0) if centre is None else np.asarray(centre, float)

    # 遠方円上の目標点: 弧長で割り付けると必ず単調
    seg = np.linalg.norm(np.roll(p, -1, axis=0) - p, axis=1)
    s = np.concatenate([[0.0], np.cumsum(seg)[:-1]]) / seg.sum()
    ang0 = np.arctan2(p[0, 1] - centre[1], p[0, 0] - centre[0])
    ang = ang0 + 2.0 * np.pi * s
    outer = centre + far_field_radius * np.stack([np.cos(ang), np.sin(ang)], axis=1)

    nrm = _node_normals(p)
    length = _geometric(n_radial, far_field_radius, radial_grading)
    t = length / length[-1]
    # 法線押し出しは壁から ``normal_length`` までで, そこから先は遠方円への
    # 直線に滑らかに移す. 押し出し距離が断面の曲率半径を超えると法線どうしが
    # 交差してセルが潰れるため, パラメータ t ではなく**物理距離**で切る.
    u = np.clip(length / max(normal_length, 1e-12), 0.0, 1.0)
    b = u * u * (3.0 - 2.0 * u)      # smoothstep (両端で傾き 0)

    a = p[:, None, :] + nrm[:, None, :] * length[None, :, None]
    sray = p[:, None, :] + (outer - p)[:, None, :] * t[None, :, None]
    x = (1.0 - b)[None, :, None] * a + b[None, :, None] * sray

    # 周方向の平滑化 (法線の食い違いで生じる折れを均す). 壁と最外層は固定,
    # 内側ほど弱くして境界層の直交性を保つ.
    if smooth_passes > 0 and n_radial > 1:
        w = smooth_weight * b[1:-1]
        for _ in range(smooth_passes):
            mid = x[:, 1:-1, :]
            lap = 0.5 * (np.roll(mid, -1, axis=0) + np.roll(mid, 1, axis=0)) - mid
            x[:, 1:-1, :] = mid + w[None, :, None] * lap

    bad = cell_areas(x) <= 0.0
    if bad.any():
        i, k = np.argwhere(bad)[0]
        raise ValueError(
            f"O 型格子のセル ({i}, {k}) の面積が非正です. "
            "normal_length を小さくするか smooth_passes を増やしてください"
        )
    return x


def cell_areas(nodes: np.ndarray) -> np.ndarray:
    """``(n_theta, n_radial)`` の四辺形セル面積 (符号つき).

    断面が反時計回りなので 半径外向き r と周方向 t は ``r x t = +z``.
    セルを (i,k) -> (i,k+1) -> (i+1,k+1) -> (i+1,k) の順 (= r のあと t)
    に回れば正の面積になる.
    """
    x = np.asarray(nodes, float)
    nxt = np.roll(x, -1, axis=0)
    a = x[:, :-1, :]
    b = x[:, 1:, :]
    c = nxt[:, 1:, :]
    d = nxt[:, :-1, :]
    # 四辺形 a-b-c-d の符号つき面積 (反時計回りで正)
    def cross(u, v):
        return u[..., 0] * v[..., 1] - u[..., 1] * v[..., 0]
    return 0.5 * (cross(a, b) + cross(b, c) + cross(c, d) + cross(d, a))


# ------------------------------------------------------------- polyMesh 出力
def write_polymesh(
    directory,
    nodes: np.ndarray,
    *,
    span: float = 0.1,
    wall_patch: str = "airfoil",
    far_patch: str = "farfield",
    empty_patch: str = "frontAndBack",
) -> Path:
    """構造 O 型格子を OpenFOAM の ``constant/polyMesh`` に書き出す."""
    x = np.asarray(nodes, float)
    nt, nk1, _ = x.shape
    nr = nk1 - 1
    n_node = nt * nk1

    def nid(i, k, z):
        return z * n_node + k * nt + i

    def cid(i, k):
        return k * nt + i

    ii = np.arange(nt)
    jj = (ii + 1) % nt

    faces: list[np.ndarray] = []
    owner: list[np.ndarray] = []
    neigh: list[np.ndarray] = []

    # (a) 周方向に隣り合うセルの間の面 (法線は +t)
    for k in range(nr):
        v = np.stack([nid(jj, k, 0), nid(jj, k, 1),
                      nid(jj, k + 1, 1), nid(jj, k + 1, 0)], axis=1)
        faces.append(v)
        owner.append(cid(ii, k))
        neigh.append(cid(jj, k))
    # (b) 半径方向に隣り合うセルの間の面 (法線は +r)
    for k in range(nr - 1):
        v = np.stack([nid(ii, k + 1, 0), nid(jj, k + 1, 0),
                      nid(jj, k + 1, 1), nid(ii, k + 1, 1)], axis=1)
        faces.append(v)
        owner.append(cid(ii, k))
        neigh.append(cid(ii, k + 1))

    fv = np.concatenate(faces)
    fo = np.concatenate(owner)
    fn = np.concatenate(neigh)
    # owner < neighbour になるよう向きを揃える
    swap = fo > fn
    fv[swap] = fv[swap][:, ::-1]
    fo[swap], fn[swap] = fn[swap], fo[swap].copy()
    order = np.lexsort((fn, fo))          # upper-triangular order
    fv, fo, fn = fv[order], fo[order], fn[order]

    # 境界面
    wall = np.stack([nid(ii, 0, 0), nid(ii, 0, 1),
                     nid(jj, 0, 1), nid(jj, 0, 0)], axis=1)
    wall_own = cid(ii, 0)
    far = np.stack([nid(ii, nr, 0), nid(jj, nr, 0),
                    nid(jj, nr, 1), nid(ii, nr, 1)], axis=1)
    far_own = cid(ii, nr - 1)

    zmin, zmax, z_own = [], [], []
    for k in range(nr):
        zmin.append(np.stack([nid(ii, k, 0), nid(jj, k, 0),
                              nid(jj, k + 1, 0), nid(ii, k + 1, 0)], axis=1))
        zmax.append(np.stack([nid(ii, k, 1), nid(ii, k + 1, 1),
                              nid(jj, k + 1, 1), nid(jj, k, 1)], axis=1))
        z_own.append(cid(ii, k))
    z_faces = np.concatenate(zmin + zmax)
    z_own = np.concatenate(z_own + z_own)

    all_faces = np.concatenate([fv, wall, far, z_faces])
    all_owner = np.concatenate([fo, wall_own, far_own, z_own])

    pts = np.empty((2 * n_node, 3))
    flat = x.transpose(1, 0, 2).reshape(-1, 2)      # k-major, i-minor
    pts[:n_node, :2] = flat
    pts[:n_node, 2] = 0.0
    pts[n_node:, :2] = flat
    pts[n_node:, 2] = span

    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    (d / "points").write_text(
        _HEADER.format(cls="vectorField", obj="points")
        + f"{len(pts)}\n(\n"
        + "\n".join(f"({a:.10g} {b:.10g} {c:.10g})" for a, b, c in pts)
        + "\n)\n"
    )
    (d / "faces").write_text(
        _HEADER.format(cls="faceList", obj="faces")
        + f"{len(all_faces)}\n(\n"
        + "\n".join("4(" + " ".join(map(str, f)) + ")" for f in all_faces)
        + "\n)\n"
    )
    (d / "owner").write_text(
        _HEADER.format(cls="labelList", obj="owner")
        + f"{len(all_owner)}\n(\n"
        + "\n".join(map(str, all_owner)) + "\n)\n"
    )
    (d / "neighbour").write_text(
        _HEADER.format(cls="labelList", obj="neighbour")
        + f"{len(fn)}\n(\n" + "\n".join(map(str, fn)) + "\n)\n"
    )
    start = len(fv)
    patches = [
        (wall_patch, "wall", len(wall), start),
        (far_patch, "patch", len(far), start + len(wall)),
        (empty_patch, "empty", len(z_faces), start + len(wall) + len(far)),
    ]
    body = "".join(
        f"    {name}\n    {{\n        type            {typ};\n"
        + (f"        inGroups        1({typ});\n" if typ == "wall" else "")
        + f"        nFaces          {nf};\n        startFace       {sf};\n    }}\n"
        for name, typ, nf, sf in patches
    )
    (d / "boundary").write_text(
        _HEADER.format(cls="polyBoundaryMesh", obj="boundary")
        + f"{len(patches)}\n(\n{body})\n"
    )
    return d
