"""OpenFOAM を使った 2 次元翼型 CFD.

なぜ 2 次元翼型なのか
---------------------
本パッケージで残っている最大の不確かさは **Re = 2,000 - 20,000 の翼型
ポーラ** であって, 3 次元の渦構造ではない (Lv3 の渦法が BEMT と 0.6 % で
一致することで確認済み). したがって費用対効果がいちばん高い CFD は
**断面まわりの 2 次元計算**である.

    翼断面 (SectionShape)  --CFD-->  cl(alpha, Re), cd(alpha, Re)
                                        |
                                        v
                                  TabulatedAirfoil  --> BEMT / 渦法

これで :func:`~prop_sim.section.airfoil_from_section` の経験補正
(``camber_efficiency`` / ``bubble_penalty`` / ``reynolds_lift_slope``) を
物理計算に置き換えられる.

格子
----
断面まわりの **O 型格子**を blockMesh で生成する. 断面を N 点で離散化し,
各周方向区間ごとに 1 ブロック (半径方向 n_r セル) を置く. 後縁に厚みが
ある断面 (射出成型のマイクロプロペラは 1-3 %c ある) では O 型格子が
そのまま使えて素直.

解法
----
Re が 10^4 前後なので層流. 定常 ``simpleFoam`` で解き, 残差が落ちない
(剥離による非定常) 場合は ``pimpleFoam`` に切り替えて時間平均をとる.

制限
----
* **3 次元ロータ CFD はここでは回さない**. 滑りメッシュ RANS は
  数百万セル・数時間〜数日で, 本パッケージの想定外.
  外部で回した結果は :meth:`SurrogateModel.from_conditions` で取り込める.
* Re < 10^4 の層流剥離泡は 2 次元計算でも難しい. 2 次元では剥離せん断層の
  3 次元不安定が表現できず, 剥離泡が実際より大きく出る傾向がある.
  結果は「経験式より根拠がある推定」であって真値ではない.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from ..airfoil import TabulatedAirfoil
from ..section import SectionShape
from .foam_io import PolyMesh, patch_wrench
from .mesh import ogrid_nodes, write_polymesh

__all__ = [
    "OpenFoamCase",
    "AirfoilCaseConfig",
    "find_openfoam",
    "surface_points",
    "polygon_centroid",
    "build_blockmesh_dict",
    "run_polar",
    "read_force_coefficients",
    "integrate_coefficients",
]

_ENV_CANDIDATES = (
    "/usr/share/openfoam/etc/bashrc",
    "/usr/lib/openfoam/openfoam2306/etc/bashrc",
    "/opt/openfoam12/etc/bashrc",
)

_HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| generated by prop_sim.cfd.openfoam                                          |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    {extra}object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def _head(cls: str, obj: str, location: str | None = None) -> str:
    extra = f'location    "{location}";\n    ' if location else ""
    return _HEADER.format(cls=cls, obj=obj, extra=extra)


def find_openfoam() -> str | None:
    """OpenFOAM の ``etc/bashrc`` を探す. 見つからなければ None."""
    env = os.environ.get("PROP_SIM_OPENFOAM_BASHRC")
    if env and Path(env).is_file():
        return env
    for c in _ENV_CANDIDATES:
        if Path(c).is_file():
            return c
    if shutil.which("blockMesh") and shutil.which("simpleFoam"):
        return ""          # すでに PATH が通っている
    return None


# --------------------------------------------------------------------- 形状
def surface_points(
    section: SectionShape, n: int = 160, te_gap_min: float = 1.0e-4
) -> np.ndarray:
    """断面の閉曲線を反時計回りに ``n`` 点で離散化する.

    後縁上面 -> 前縁 -> 後縁下面 の順に並べ, 後縁に厚みがあればそのまま
    base 面として閉じる (重複点は作らない).
    """
    s = section.resample(max(n // 2 + 1, 8))
    up = np.stack([s.x, s.upper], axis=1)
    lo = np.stack([s.x, s.lower], axis=1)
    if abs(up[-1, 1] - lo[-1, 1]) < te_gap_min:      # 鋭い後縁 -> 1 点に統合
        pts = np.vstack([up[::-1], lo[1:-1]])
    else:
        pts = np.vstack([up[::-1], lo[1:]])
    if abs(pts[0, 1] - pts[-1, 1]) < te_gap_min and abs(pts[0, 0] - pts[-1, 0]) < 1e-12:
        pts = pts[:-1]
    # 反時計回りに揃える (blockMesh のブロックが inside-out にならないように)
    area = 0.5 * np.sum(pts[:, 0] * np.roll(pts[:, 1], -1)
                        - np.roll(pts[:, 0], -1) * pts[:, 1])
    if area < 0.0:
        pts = pts[::-1]
    return pts


def polygon_centroid(points: np.ndarray) -> np.ndarray:
    """閉多角形の図心. 面積が潰れている場合は頂点の平均に落とす."""
    p = np.asarray(points, float)
    q = np.roll(p, -1, axis=0)
    cross = p[:, 0] * q[:, 1] - q[:, 0] * p[:, 1]
    a = 0.5 * cross.sum()
    if abs(a) < 1e-12:
        return p.mean(axis=0)
    return ((p + q) * cross[:, None]).sum(axis=0) / (6.0 * a)


def build_blockmesh_dict(
    points: np.ndarray,
    *,
    far_field_radius: float = 20.0,
    n_radial: int = 90,
    radial_grading: float = 3000.0,
    span: float = 0.1,
    centre=None,
) -> str:
    """O 型格子の ``blockMeshDict`` を生成する.

    Parameters
    ----------
    points:
        断面の閉曲線 ``(N, 2)`` (コード長 1 に正規化, 反時計回り).
    far_field_radius:
        遠方境界の半径 (コード長基準).
    n_radial, radial_grading:
        半径方向のセル数と, 最外セル / 最内セル の比.
    span:
        2 次元計算の z 方向の厚み.
    centre:
        遠方円の中心. ``None`` なら断面の図心を使う. キャンバの大きい
        薄翼では 1/4 コード点 ``(0.25, 0)`` が断面の**外**に出てしまい
        O 型格子が破綻するため, 図心を既定にしてある.
    """
    p = np.asarray(points, dtype=float)
    n = p.shape[0]
    centre = polygon_centroid(p) if centre is None else np.asarray(centre, float)

    # 遠方境界の点は中心からの偏角で割り付ける (放射線が断面にほぼ直交する).
    # ただし断面が中心について星形でないと偏角が逆行してブロックが裏返るので,
    # 最小刻み ``dmin`` を課して単調化し, 合計がちょうど 2 pi になるよう
    # 正規化する. 中心が断面の内部にあれば, この補正はほとんど効かない.
    ang = np.unwrap(np.arctan2(p[:, 1] - centre[1], p[:, 0] - centre[0]))
    d = np.diff(np.concatenate([ang, [ang[0] + 2.0 * np.pi]]))
    d = np.maximum(d, 0.2 * 2.0 * np.pi / n)
    d *= 2.0 * np.pi / d.sum()
    ang = ang[0] + np.concatenate([[0.0], np.cumsum(d)[:-1]])
    outer = centre + far_field_radius * np.stack([np.cos(ang), np.sin(ang)], axis=1)

    # 右手系になっているか (局所 x = 半径方向, 局所 y = 周方向)
    radial = outer - p
    circ = np.roll(outer, -1, axis=0) - outer
    twist = radial[:, 0] * circ[:, 1] - radial[:, 1] * circ[:, 0]
    if np.any(twist <= 0.0):
        bad = int(np.argmin(twist))
        raise ValueError(
            f"O 型格子のブロック {bad} が裏返ります "
            f"(断面が中心 {tuple(centre)} について星形でない可能性). "
            "surface_points の点数を増やすか centre を変えてください"
        )
    # 放射線が断面に対して寝すぎていないか (blockMesh の面法線チェック対策)
    tang = np.roll(p, -1, axis=0) - p
    ok = np.linalg.norm(tang, axis=1) > 0
    cosang = np.abs(np.einsum("ij,ij->i", radial[ok], tang[ok])) / (
        np.linalg.norm(radial[ok], axis=1) * np.linalg.norm(tang[ok], axis=1))
    if cosang.max() > 0.999:
        raise ValueError(
            "放射線が断面表面とほぼ平行になっています "
            f"(cos = {cosang.max():.4f}, ブロック {int(np.argmax(cosang))})"
        )

    verts = []
    for z in (0.0, span):
        for arr in (p, outer):
            verts.extend(f"    ({x:.10g} {y:.10g} {z:.10g})" for x, y in arr)
    # 添字: s(z0)=i, o(z0)=n+i, s(z1)=2n+i, o(z1)=3n+i
    #
    # ブロックの局所座標は (x, y, z) = (半径外向き, 周方向, スパン方向).
    # 断面を反時計回りに並べてあるので 周方向 t と外向き r は t x r = -z,
    # つまり (周, 半径, スパン) の順だと左手系になり blockMesh が
    # "is inside-out" で落ちる. r x t = +z なので半径方向を局所 x に取る.
    blocks, airfoil, farfield, back, front = [], [], [], [], []
    for i in range(n):
        j = (i + 1) % n
        v = (i, n + i, n + j, j, 2 * n + i, 3 * n + i, 3 * n + j, 2 * n + j)
        blocks.append(
            f"    hex ({' '.join(map(str, v))}) ({n_radial} 1 1) "
            f"simpleGrading ({radial_grading:g} 1 1)"
        )
        # blockMesh の面規約: x-min (0 4 7 3), x-max (1 2 6 5),
        #                     z-min (0 3 2 1), z-max (4 5 6 7)
        airfoil.append(f"        ({v[0]} {v[4]} {v[7]} {v[3]})")
        farfield.append(f"        ({v[1]} {v[2]} {v[6]} {v[5]})")
        back.append(f"        ({v[0]} {v[3]} {v[2]} {v[1]})")
        front.append(f"        ({v[4]} {v[5]} {v[6]} {v[7]})")

    return (
        _head("dictionary", "blockMeshDict", "system")
        + "\nscale   1;\n\nvertices\n(\n"
        + "\n".join(verts)
        + "\n);\n\nblocks\n(\n"
        + "\n".join(blocks)
        + "\n);\n\nedges\n(\n);\n\nboundary\n(\n"
        + "    airfoil\n    {\n        type wall;\n        faces\n        (\n"
        + "\n".join(airfoil)
        + "\n        );\n    }\n"
        + "    farfield\n    {\n        type patch;\n        faces\n        (\n"
        + "\n".join(farfield)
        + "\n        );\n    }\n"
        + "    frontAndBack\n    {\n        type empty;\n        faces\n        (\n"
        + "\n".join(back + front)
        + "\n        );\n    }\n);\n\nmergePatchPairs\n(\n);\n"
    )


# ------------------------------------------------------------------ ケース
@dataclass
class AirfoilCaseConfig:
    """2 次元翼型ケースの設定."""

    reynolds: float = 1.2e4
    alpha_deg: float = 0.0
    u_inf: float = 1.0          # コード長 1 m, U=1 m/s とすれば nu = 1/Re
    n_surface: int = 160
    n_radial: int = 90
    far_field_radius: float = 20.0
    radial_grading: float = 3000.0
    span: float = 0.1
    solver: str = "simpleFoam"
    end_time: float = 3000.0     # simpleFoam では反復回数
    write_interval: float = 1000.0
    delta_t: float = 1.0
    residual_tol: float = 1.0e-6
    n_procs: int = 1
    average_last_fraction: float = 0.25   # 非定常のとき後半何割を平均するか
    #: ``forceCoeffs`` functionObject を使うか. 既定は使わず, 書き出された
    #: 場から :mod:`prop_sim.cfd.foam_io` で積分する (モジュール docstring 参照).
    use_function_objects: bool = False
    #: ``"ogrid"`` = 自前の O 型格子 (既定), ``"blockmesh"`` = blockMesh.
    #: 薄くキャンバの大きい断面では blockMesh 版は破綻する
    #: (:mod:`prop_sim.cfd.mesh` の docstring 参照).
    mesh: str = "ogrid"
    normal_length: float = 0.5     # 壁法線押し出しを効かせる距離 (コード基準)
    smooth_passes: int = 120       # 周方向平滑化の回数
    max_courant: float = 3.0       # 非定常ソルバの Courant 数上限
    keep_all_times: bool = False   # 全時刻を残す (時刻歴を見たいとき)
    restart: bool = False          # 既存の最終時刻から続きを解く


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


@dataclass
class OpenFoamCase:
    """OpenFOAM ケースディレクトリの生成と実行."""

    directory: Path
    section: SectionShape
    config: AirfoilCaseConfig = field(default_factory=AirfoilCaseConfig)

    def __post_init__(self) -> None:
        self.directory = Path(self.directory)

    # ------------------------------------------------------------- 生成
    def write(self) -> Path:
        """ケース一式を書き出す (OpenFOAM が無くても実行できる)."""
        c = self.config
        d = self.directory
        if d.exists() and not c.restart:
            shutil.rmtree(d)
        a = np.deg2rad(c.alpha_deg)
        u = (c.u_inf * np.cos(a), c.u_inf * np.sin(a), 0.0)
        nu = c.u_inf * 1.0 / c.reynolds          # コード長 = 1 m

        pts = surface_points(self.section, c.n_surface)
        if c.mesh == "ogrid":
            d.mkdir(parents=True, exist_ok=True)
            write_polymesh(d / "constant/polyMesh", ogrid_nodes(
                pts, n_radial=c.n_radial, far_field_radius=c.far_field_radius,
                radial_grading=c.radial_grading, normal_length=c.normal_length,
                smooth_passes=c.smooth_passes), span=c.span)
        elif c.mesh == "blockmesh":
            _write(d / "system/blockMeshDict", build_blockmesh_dict(
                pts, far_field_radius=c.far_field_radius, n_radial=c.n_radial,
                radial_grading=c.radial_grading, span=c.span))
        else:
            raise ValueError(f"未知の mesh: {c.mesh!r}")
        _write(d / "system/controlDict", self._control_dict(u))
        _write(d / "system/fvSchemes", _FV_SCHEMES[c.solver])
        _write(d / "system/fvSolution", _FV_SOLUTION[c.solver])
        _write(d / "system/decomposeParDict", _decompose(c.n_procs))
        _write(d / "constant/transportProperties",
               _head("dictionary", "transportProperties", "constant")
               + f"\ntransportModel  Newtonian;\n\nnu              {nu:.8g};\n")
        _write(d / "constant/turbulenceProperties",
               _head("dictionary", "turbulenceProperties", "constant")
               + "\nsimulationType  laminar;\n")
        _write(d / "0/U", _field_u(u))
        _write(d / "0/p", _field_p())
        return d

    def _control_dict(self, u) -> str:
        c = self.config
        a = np.deg2rad(c.alpha_deg)
        mag = float(np.hypot(u[0], u[1]))
        if not c.use_function_objects:
            unsteady = c.solver != "simpleFoam"
            # 非定常なら Courant 数で刻みを自動調整し, 書き出しは実時間基準.
            # 定常 (simpleFoam) では endTime = 反復回数.
            extra = (
                f"adjustTimeStep  yes;\nmaxCo           {c.max_courant:g};\n"
                f"maxDeltaT       {c.write_interval:g};\n"
                if unsteady else ""
            )
            n_keep = max(int(round(1.0 / max(c.average_last_fraction, 1e-9))), 2)
            return (
                _head("dictionary", "controlDict", "system")
                + f"""
application     {c.solver};
startFrom       {"latestTime" if c.restart else "startTime"};
startTime       0;
stopAt          endTime;
endTime         {c.end_time:g};
deltaT          {c.delta_t:g};
writeControl    {"adjustableRunTime" if unsteady else "timeStep"};
writeInterval   {c.write_interval:g};
purgeWrite      {0 if c.keep_all_times else n_keep};
writeFormat     ascii;
writePrecision  8;
timeFormat      general;
timePrecision   8;
runTimeModifiable false;
{extra}
functions
{{
}}
"""
            )
        return (
            _head("dictionary", "controlDict", "system")
            + f"""
application     {c.solver};
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {c.end_time:g};
deltaT          {c.delta_t:g};
writeControl    timeStep;
writeInterval   {c.write_interval:g};
purgeWrite      2;
writeFormat     ascii;
writePrecision  8;
runTimeModifiable true;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   1;
        log             no;
        patches         (airfoil);
        rho             rhoInf;
        rhoInf          1;
        CofR            (0.25 0 0);
        liftDir         ({-np.sin(a):.10g} {np.cos(a):.10g} 0);
        dragDir         ({np.cos(a):.10g} {np.sin(a):.10g} 0);
        pitchAxis       (0 0 1);
        magUInf         {mag:.10g};
        lRef            1;
        Aref            {c.span:.10g};
    }}
    residuals
    {{
        type            solverInfo;
        libs            ("libutilityFunctionObjects.so");
        fields          (U p);
        writeResidualFields no;
    }}
}}
"""
        )

    # ------------------------------------------------------------- 実行
    def run(self, bashrc: str | None = None, timeout: float = 3600.0) -> dict:
        """blockMesh -> ソルバ を実行する."""
        bashrc = find_openfoam() if bashrc is None else bashrc
        if bashrc is None:
            raise RuntimeError(
                "OpenFOAM が見つかりません "
                "(PROP_SIM_OPENFOAM_BASHRC 環境変数で etc/bashrc を指定できます)"
            )
        src = f"source {bashrc} >/dev/null 2>&1; " if bashrc else ""
        log = {}
        steps = (("blockMesh",) if self.config.mesh == "blockmesh" else ()) + (
            self.config.solver,)
        for cmd in steps:
            # 進捗が見えるようログへ直接リダイレクトする (長い計算になるため)
            logfile = self.directory / f"log.{cmd}"
            r = subprocess.run(
                ["bash", "-c", f"set -a; {src}set +a; cd {self.directory} && "
                               f"{cmd} > {logfile.name} 2>&1"],
                capture_output=True, text=True, timeout=timeout,
            )
            log[cmd] = r.returncode
            if r.returncode != 0:
                tail = logfile.read_text()[-1500:] if logfile.is_file() else r.stderr
                raise RuntimeError(f"{cmd} が失敗しました (log.{cmd} 参照)\n{tail}")
        return log

    # ------------------------------------------------------------- 結果
    def coefficients(self) -> dict[str, float]:
        """``Cl`` / ``Cd`` / ``CmPitch`` を返す.

        ``use_function_objects`` が偽 (既定) のときは書き出された場を
        :func:`~prop_sim.cfd.foam_io.patch_wrench` で積分する. 複数の
        時刻が残っていれば後半 ``average_last_fraction`` を平均し,
        そのばらつきを ``*_std`` として返す (非定常性の指標).
        """
        if self.config.use_function_objects:
            return read_force_coefficients(
                self.directory, self.config.average_last_fraction)
        return integrate_coefficients(
            self.directory, self.config, patch="airfoil")


def _written_times(case_dir) -> list[str]:
    out = []
    for p in Path(case_dir).iterdir():
        if not p.is_dir() or not (p / "U").is_file():
            continue
        try:
            out.append((float(p.name), p.name))
        except ValueError:
            pass
    return [n for _, n in sorted(out)]


def integrate_coefficients(
    case_dir, config: AirfoilCaseConfig | None = None, *, patch: str = "airfoil"
) -> dict[str, float]:
    """壁面荷重を積分して空力係数にする (functionObject 不要).

    ``controlDict`` の ``purgeWrite`` が ``1 / average_last_fraction`` 回分
    だけ残すようにしてあるので, 初期値 (``0``) 以外の残っている時刻を
    すべて平均する. 定常計算なら 1 個しか残らず, そのまま最終解になる.

    ``CmPitch`` は 1/4 コードまわり・**頭上げが正** (``Airfoil.cm`` と同じ).
    """
    case_dir = Path(case_dir)
    c = config or AirfoilCaseConfig()
    times = _written_times(case_dir)
    if not times:
        raise FileNotFoundError(f"{case_dir} に書き出された場がありません")
    if len(times) > 1:
        times = [t for t in times if float(t) > 0.0] or times[-1:]

    a = np.deg2rad(c.alpha_deg)
    drag_dir = np.array([np.cos(a), np.sin(a), 0.0])
    lift_dir = np.array([-np.sin(a), np.cos(a), 0.0])
    q = 0.5 * c.u_inf**2 * c.span          # rho = 1, lRef = Aref/span = 1
    # 幾何モーメント Mz = sum (r x F)_z は, x が下流・y が上向きのとき
    # **頭下げ**が正になる (前縁は -x 側にあるため). 空力の慣用
    # (頭上げが正, `Airfoil.cm` と同じ) に合わせて符号を反転する.
    cm_sign = -1.0

    mesh = None
    cl, cd, cm, fp, fv = [], [], [], [], []
    for t in times:
        w = patch_wrench(case_dir, patch, time=t, rho=1.0, mesh=mesh)
        mesh = w["mesh"]
        cl.append(float(w["force"] @ lift_dir) / q)
        cd.append(float(w["force"] @ drag_dir) / q)
        cm.append(cm_sign * float(w["moment"][2]) / q)
        fp.append(float(w["force_pressure"] @ drag_dir) / q)
        fv.append(float(w["force_viscous"] @ drag_dir) / q)
    out = {
        "Cl": float(np.mean(cl)), "Cd": float(np.mean(cd)),
        "CmPitch": float(np.mean(cm)),
        "Cl_std": float(np.std(cl)), "Cd_std": float(np.std(cd)),
        "CmPitch_std": float(np.std(cm)),
        "Cd_pressure": float(np.mean(fp)), "Cd_viscous": float(np.mean(fv)),
        "n_samples": float(len(times)), "t_end": float(times[-1]),
    }
    return out


def read_force_coefficients(
    case_dir, average_last_fraction: float = 0.25
) -> dict[str, float]:
    """``postProcessing/forceCoeffs/*/coefficient*.dat`` を読む.

    後半 ``average_last_fraction`` を時間平均し, その区間の標準偏差
    (``cl_std`` 等) も返す — 非定常かどうかの判定に使える.
    """
    case_dir = Path(case_dir)
    files = sorted((case_dir / "postProcessing" / "forceCoeffs").glob("*/coeff*.dat"))
    if not files:
        raise FileNotFoundError(f"{case_dir} に forceCoeffs の出力がありません")
    header, rows = [], []
    for f in files:
        for line in f.read_text().splitlines():
            if line.startswith("#"):
                if "Time" in line:
                    header = line.lstrip("#").split()
                continue
            rows.append([float(v) for v in line.split()])
    if not rows:
        raise ValueError("forceCoeffs の出力が空です")
    data = np.asarray(rows)
    order = np.argsort(data[:, 0])
    data = data[order]
    n = max(int(data.shape[0] * average_last_fraction), 1)
    tail = data[-n:]
    out = {"n_samples": float(data.shape[0]), "t_end": float(data[-1, 0])}
    for k, name in enumerate(header):
        if k == 0:
            continue
        key = name.replace("(", "").replace(")", "")
        out[key] = float(tail[:, k].mean())
        out[key + "_std"] = float(tail[:, k].std())
    return out


# ---------------------------------------------------------------- ポーラ
def run_polar(
    section: SectionShape,
    alphas_deg,
    reynolds: float = 1.2e4,
    *,
    workdir="cfd_runs",
    config: AirfoilCaseConfig | None = None,
    bashrc: str | None = None,
    timeout: float = 3600.0,
    progress: bool = True,
    keep_cases: bool = False,
) -> dict:
    """迎角を振って cl, cd を求め, :class:`TabulatedAirfoil` を作る.

    Returns
    -------
    dict
        ``alpha_deg``, ``cl``, ``cd``, ``cm``, ``cl_std``, ``cd_std``,
        ``airfoil`` (:class:`TabulatedAirfoil`), ``cases``.
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    alphas = np.atleast_1d(np.asarray(alphas_deg, dtype=float))
    base = config or AirfoilCaseConfig()
    cl, cd, cm, cls_, cds, cases = [], [], [], [], [], []
    for a in alphas:
        cfg = AirfoilCaseConfig(**{**base.__dict__, "alpha_deg": float(a),
                                   "reynolds": float(reynolds)})
        cdir = workdir / f"a{a:+06.2f}_Re{reynolds:.0f}".replace("+", "p").replace(
            "-", "m")
        case = OpenFoamCase(cdir, section, cfg)
        case.write()
        if progress:  # pragma: no cover
            print(f"  CFD alpha={a:+.2f} deg, Re={reynolds:.0f} ...", flush=True)
        case.run(bashrc=bashrc, timeout=timeout)
        c = case.coefficients()
        cl.append(c.get("Cl", np.nan))
        cd.append(c.get("Cd", np.nan))
        cm.append(c.get("CmPitch", c.get("Cm", np.nan)))
        cls_.append(c.get("Cl_std", np.nan))
        cds.append(c.get("Cd_std", np.nan))
        cases.append(cdir)
        if not keep_cases:
            for sub in cdir.glob("[0-9]*"):
                if sub.is_dir() and sub.name != "0":
                    shutil.rmtree(sub, ignore_errors=True)
    cl, cd, cm = map(np.asarray, (cl, cd, cm))
    return {
        "alpha_deg": alphas, "cl": cl, "cd": cd, "cm": cm,
        "cl_std": np.asarray(cls_), "cd_std": np.asarray(cds),
        "reynolds": reynolds, "cases": cases,
        "airfoil": TabulatedAirfoil(
            alpha_deg=alphas, cl=cl, cd=cd, cm=cm,
            name=f"{section.name} CFD Re={reynolds:.0f}",
            reynolds_ref=reynolds, aspect_ratio=3.0),
    }


# ------------------------------------------------------------- 固定辞書
def _field_u(u) -> str:
    return (
        _head("volVectorField", "U", "0")
        + f"""
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform ({u[0]:.10g} {u[1]:.10g} 0);

boundaryField
{{
    airfoil       {{ type noSlip; }}
    farfield      {{ type freestream; freestreamValue uniform
                     ({u[0]:.10g} {u[1]:.10g} 0); }}
    frontAndBack  {{ type empty; }}
}}
"""
    )


def _field_p() -> str:
    return (
        _head("volScalarField", "p", "0")
        + """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    airfoil       { type zeroGradient; }
    farfield      { type freestreamPressure; freestreamValue uniform 0; }
    frontAndBack  { type empty; }
}
"""
    )


def _decompose(n: int) -> str:
    return (
        _head("dictionary", "decomposeParDict", "system")
        + f"\nnumberOfSubdomains {max(n,1)};\n\nmethod          scotch;\n"
    )


_FV_SCHEMES = {
    "simpleFoam": _head("dictionary", "fvSchemes", "system") + """
ddtSchemes      { default steadyState; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }
wallDist        { method meshWave; }
""",
    "pimpleFoam": _head("dictionary", "fvSchemes", "system") + """
ddtSchemes      { default backward; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      Gauss linearUpwind grad(U);
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }
wallDist        { method meshWave; }
""",
}

_FV_SOLUTION = {
    "simpleFoam": _head("dictionary", "fvSolution", "system") + """
solvers
{
    p   { solver GAMG; tolerance 1e-08; relTol 0.01;
          smoother GaussSeidel; }
    U   { solver smoothSolver; smoother symGaussSeidel;
          tolerance 1e-09; relTol 0.01; }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl { p 1e-6; U 1e-7; }
}

relaxationFactors
{
    equations { U 0.9; }
}
""",
    "pimpleFoam": _head("dictionary", "fvSolution", "system") + """
solvers
{
    p     { solver GAMG; tolerance 1e-08; relTol 0.01;
            smoother GaussSeidel; }
    pFinal { $p; relTol 0; }
    "(U|UFinal)" { solver smoothSolver; smoother symGaussSeidel;
                   tolerance 1e-09; relTol 0; }
}

PIMPLE
{
    nOuterCorrectors 2;
    nCorrectors      2;
    nNonOrthogonalCorrectors 1;
}
""",
}
